# Generated by Django 2.0.3 on 2018-12-13 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_auto_20181115_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCWTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyframe_count', models.PositiveIntegerField()),
                ('unchecked_count', models.PositiveIntegerField()),
                ('checked_count', models.PositiveIntegerField()),
                ('need_modify_count', models.PositiveIntegerField()),
                ('priority', models.PositiveIntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Task')),
            ],
        ),
    ]
