# Generated by Django 2.0.3 on 2018-12-14 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_fcwtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCWTest_FrameUserRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.PositiveIntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('checker', models.CharField(max_length=150)),
                ('current', models.BooleanField(default=False)),
                ('user_submit', models.BooleanField(default=False)),
                ('need_modify', models.BooleanField(default=False)),
                ('checked', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=2048)),
                ('extraCategory', models.CharField(max_length=256)),
                ('defaultCategory', models.CharField(max_length=256)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Task')),
            ],
        ),
        migrations.AddField(
            model_name='fcwtest',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fcwtest',
            name='checker',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fcwtest',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fcwtest',
            name='need_modify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fcwtest',
            name='user',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fcwtest',
            name='userGet_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fcwtest',
            name='userModifyGet_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fcwtest',
            name='userModifySave_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fcwtest',
            name='userModifySubmit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fcwtest',
            name='userSave_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fcwtest',
            name='userSubmit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fcwtest',
            name='user_submit',
            field=models.BooleanField(default=False),
        ),
    ]
