# Generated by Django 2.0.3 on 2018-12-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_fcwtest_fcwtest_frameuserrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeledbox',
            name='grouping',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='labeledpoints',
            name='grouping',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='labeledpolygon',
            name='grouping',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='labeledpolyline',
            name='grouping',
            field=models.CharField(default='', max_length=32),
        ),
    ]
