# Generated by Django 2.0.3 on 2019-01-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0015_task_packagename'),
    ]

    operations = [
        migrations.AddField(
            model_name='apacorner_frameuserrecord',
            name='packagename',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='fcwtest_frameuserrecord',
            name='packagename',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='taskframeuserrecord',
            name='packagename',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='task',
            name='packagename',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
