# Generated by Django 2.0.3 on 2019-01-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0017_auto_20190115_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='apacorner',
            name='checked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apacorner',
            name='need_modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fcwtest',
            name='checked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fcwtest',
            name='need_modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskframeuserrecord',
            name='checked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskframeuserrecord',
            name='need_modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
