# Generated by Django 2.0.3 on 2019-01-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0018_auto_20190119_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWorkSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=150)),
                ('project', models.CharField(default='', max_length=150)),
                ('packagename', models.CharField(default='', max_length=1024)),
            ],
        ),
    ]
