# Generated by Django 2.0.3 on 2019-03-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0021_dmstrain_dmstrain_frameuserrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagePriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagename', models.CharField(default='', max_length=1024)),
                ('priority', models.PositiveIntegerField()),
                ('priority_out', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='apacorner',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='apacorner',
            name='priority_out',
        ),
        migrations.RemoveField(
            model_name='bsdtrain',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='bsdtrain',
            name='priority_out',
        ),
        migrations.RemoveField(
            model_name='dmstrain',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='dmstrain',
            name='priority_out',
        ),
        migrations.RemoveField(
            model_name='fcwtest',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='fcwtest',
            name='priority_out',
        ),
        migrations.RemoveField(
            model_name='fcwtrain',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='fcwtrain',
            name='priority_out',
        ),
    ]
