# Generated by Django 2.0.3 on 2019-03-04 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0023_auto_20190304_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='packagename',
        ),
    ]
