# Generated by Django 2.0.3 on 2019-03-04 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0024_remove_task_packagename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagepriority',
            old_name='priority',
            new_name='office_priority',
        ),
        migrations.RenameField(
            model_name='packagepriority',
            old_name='priority_out',
            new_name='soho_priority',
        ),
        migrations.AlterField(
            model_name='taskpackage',
            name='packagename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.PackagePriority'),
        ),
    ]
