version: "2.3"

services:
  cvat:
    environment:
      CVAT_SHARE_URL: "Mounted from /home/jeff/TestImg host directory"

    volumes:
      - cvat_share:/home/django/share:ro
      - cvat_others:/home/django/others:ro
      
volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /home/jeff/TestImg
      o: bind
  cvat_others:
    driver_opts:
      type: none
      device: /home/jeff/Others
      o: bind